from pathlib import Path
from datetime import datetime,timedelta,timezone
import csv,random,json,textwrap
R=Path(__file__).resolve().parent; D=R/'data'; A=R/'splunk'/'after_detection_capstone_012'; L=A/'lookups'; D.mkdir(parents=True,exist_ok=True); L.mkdir(parents=True,exist_ok=True)
SEED=20260921; N=10000; rng=random.Random(SEED); base=datetime(2026,9,21,13,0,tzinfo=timezone.utc)
hosts=['HR-WS-22','ENG-WS-17','FIN-WS-09','APP-06','PATCH-01','DC-01','MGMT-01','HR-WS-08']; users=[r'ACME\\mgarcia',r'ACME\\svc_patch',r'ACME\\lchen',r'ACME\\jsmith','SYSTEM']
def ts(m=0,s=0): return (base+timedelta(minutes=m,seconds=s)).strftime('%Y-%m-%dT%H:%M:%SZ')
def noise_time(): return (base+timedelta(seconds=rng.randint(-172800,172800))).strftime('%Y-%m-%dT%H:%M:%SZ')
def write(name,special,noise):
 rows=[noise(i) for i in range(N-len(special))]+special; rows.sort(key=lambda x:x.get('_time','')); fields=list(rows[0]);
 for p in (D/name,L/name):
  with p.open('w',newline='',encoding='utf-8') as f: w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(rows)
def wt(p,s): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(textwrap.dedent(s).strip()+'\n',encoding='utf-8')
write('detection_results.csv',[
{'id':'CAP-001','_time':ts(0),'host':'HR-WS-22','user':r'ACME\\mgarcia','signal':'new scheduled task','severity':'medium','classification':'investigate'},
{'id':'CAP-002','_time':ts(19),'host':'ENG-WS-17','user':'SYSTEM','signal':'new auto-start service','severity':'high','classification':'investigate'},
{'id':'CAP-003','_time':ts(43),'host':'FIN-WS-09','user':r'ACME\\lchen','signal':'new user startup item','severity':'high','classification':'investigate'},
{'id':'CAP-004','_time':ts(61),'host':'FIN-WS-09','user':r'ACME\\jsmith','signal':'containment decision','severity':'high','classification':'response'}],lambda i:{'id':f'CAP-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'signal':rng.choice(['admin task review','service inventory','startup inventory']),'severity':rng.choice(['low','medium']),'classification':'context'})
write('scheduled_task.csv',[
{'id':'TASK-INC-1','_time':ts(0),'host':'HR-WS-22','user':r'ACME\\mgarcia','name':r'\\Microsoft\\Windows\\Update\\TelemetryCheck','command':r'C:\\ProgramData\\WinCache\\telemetry.ps1','creator':'interactive user context','run_as':r'ACME\\mgarcia','provenance':'local','classification':'investigate'},
{'id':'TASK-BEN-1','_time':ts(-30),'host':'PATCH-01','user':r'ACME\\svc_patch','name':r'\\ACME\\Patch\\TelemetryCheck','command':r'C:\\Program Files\\ACME\\Patch\\telemetry.exe','creator':'enterprise automation','run_as':r'ACME\\svc_patch','provenance':'approved change','classification':'benign'}],lambda i:{'id':f'TASK-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'name':rng.choice([r'\\ACME\\Inventory',r'\\Microsoft\\Windows\\Defrag\\ScheduledDefrag']),'command':'approved binary','creator':'enterprise automation','run_as':'SYSTEM','provenance':'approved','classification':'benign'})
write('endpoint_service.csv',[
{'id':'SVC-INC-1','_time':ts(19),'host':'ENG-WS-17','user':'SYSTEM','service':'WinSupportSvc','display':'Windows Support Service','image_path':r'C:\\ProgramData\\WinSupport\\winsupport.exe','account':'LocalSystem','creator':'remote execution from HR-WS-22','provenance':'unapproved','classification':'investigate'},
{'id':'SVC-BEN-1','_time':ts(20),'host':'APP-06','user':'SYSTEM','service':'ACMESupportAgent','display':'ACME Support Agent','image_path':r'C:\\Program Files\\ACME\\Support\\agent.exe','account':'LocalSystem','creator':'SCCM','provenance':'CHG-2026-4412','classification':'benign'}],lambda i:{'id':f'SVC-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':'SYSTEM','service':rng.choice(['Spooler','ACMEInventory','BackupAgent']),'display':'approved service','image_path':'approved path','account':'LocalSystem','creator':'endpoint management','provenance':'approved','classification':'benign'})
write('startup_config.csv',[
{'id':'START-INC-1','_time':ts(43),'host':'FIN-WS-09','user':r'ACME\\lchen','item':'OneDriveHealth','target':r'C:\\Users\\lchen\\AppData\\Roaming\\Microsoft\\OneDriveHealth\\sync.ps1','source':'user startup configuration','provenance':'local user state','classification':'investigate'},
{'id':'START-BEN-1','_time':ts(42),'host':'FIN-WS-09','user':r'ACME\\lchen','item':'MapDrives','target':r'SYSVOL\\scripts\\mapdrives.cmd','source':'enterprise logon policy','provenance':'central policy','classification':'benign'},
{'id':'START-BEN-2','_time':ts(42,10),'host':'FIN-WS-09','user':r'ACME\\lchen','item':'Teams','target':'Microsoft Teams Update','source':'application startup','provenance':'signed application','classification':'benign'}],lambda i:{'id':f'START-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'item':rng.choice(['Teams','OneDrive','MapDrives']),'target':'approved target','source':'approved startup','provenance':'approved','classification':'benign'})
write('endpoint_process.csv',[
{'id':'PROC-1','_time':ts(1),'host':'HR-WS-22','user':r'ACME\\mgarcia','parent':'taskeng.exe','process':'powershell.exe','command':'execute telemetry.ps1','classification':'investigate'},
{'id':'PROC-2','_time':ts(17),'host':'HR-WS-22','user':r'ACME\\mgarcia','parent':'powershell.exe','process':'sc.exe','command':r'create WinSupportSvc on ENG-WS-17','classification':'investigate'},
{'id':'PROC-3','_time':ts(20),'host':'ENG-WS-17','user':'SYSTEM','parent':'services.exe','process':'winsupport.exe','command':'service start','classification':'investigate'},
{'id':'PROC-4','_time':ts(44),'host':'FIN-WS-09','user':r'ACME\\lchen','parent':'explorer.exe','process':'powershell.exe','command':'execute OneDriveHealth sync.ps1','classification':'investigate'},
{'id':'PROC-BEN','_time':ts(20,5),'host':'APP-06','user':'SYSTEM','parent':'services.exe','process':'agent.exe','command':'approved support agent','classification':'benign'}],lambda i:{'id':f'PROC-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'parent':'explorer.exe','process':rng.choice(['Teams.exe','OneDrive.exe','cmd.exe']),'command':'routine activity','classification':'benign'})
write('endpoint_file.csv',[
{'id':'FILE-1','_time':ts(-2),'host':'HR-WS-22','user':r'ACME\\mgarcia','action':'create','path':r'C:\\ProgramData\\WinCache\\telemetry.ps1','process':'powershell.exe','classification':'investigate'},
{'id':'FILE-2','_time':ts(18),'host':'ENG-WS-17','user':'SYSTEM','action':'create','path':r'C:\\ProgramData\\WinSupport\\winsupport.exe','process':'remote service operation','classification':'investigate'},
{'id':'FILE-3','_time':ts(42),'host':'FIN-WS-09','user':r'ACME\\lchen','action':'create','path':r'C:\\Users\\lchen\\AppData\\Roaming\\Microsoft\\OneDriveHealth\\sync.ps1','process':'user-context process','classification':'investigate'}],lambda i:{'id':f'FILE-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'action':rng.choice(['read','create','modify']),'path':'approved operational file','process':'approved process','classification':'benign'})
write('software_trust.csv',[
{'id':'TRUST-1','_time':ts(-1),'host':'HR-WS-22','artifact':'telemetry.ps1','status':'untrusted','publisher':'','classification':'investigate'},
{'id':'TRUST-2','_time':ts(18),'host':'ENG-WS-17','artifact':'winsupport.exe','status':'untrusted','publisher':'','classification':'investigate'},
{'id':'TRUST-3','_time':ts(42),'host':'FIN-WS-09','artifact':'sync.ps1','status':'untrusted','publisher':'','classification':'investigate'},
{'id':'TRUST-BEN','_time':ts(19),'host':'APP-06','artifact':'agent.exe','status':'signed','publisher':'ACME IT','classification':'benign'}],lambda i:{'id':f'TRUST-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'artifact':'known software','status':rng.choice(['signed','trusted_internal']),'publisher':'Known Publisher','classification':'benign'})
write('network_activity.csv',[
{'id':'NET-1','_time':ts(2),'src':'HR-WS-22','dest':'203.0.113.77','user':r'ACME\\mgarcia','process':'powershell.exe','port':'443','result':'allowed','classification':'investigate'},
{'id':'NET-2','_time':ts(17),'src':'HR-WS-22','dest':'ENG-WS-17','user':r'ACME\\mgarcia','process':'sc.exe','port':'445','result':'allowed','classification':'investigate'},
{'id':'NET-3','_time':ts(21),'src':'ENG-WS-17','dest':'203.0.113.77','user':'SYSTEM','process':'winsupport.exe','port':'443','result':'allowed','classification':'investigate'},
{'id':'NET-4','_time':ts(45),'src':'FIN-WS-09','dest':'203.0.113.77','user':r'ACME\\lchen','process':'powershell.exe','port':'443','result':'allowed','classification':'investigate'}],lambda i:{'id':f'NET-N-{i:05d}','_time':noise_time(),'src':rng.choice(hosts),'dest':rng.choice(['DC-01','MGMT-01','198.51.100.20']),'user':rng.choice(users),'process':rng.choice(['Teams.exe','agent.exe','cmd.exe']),'port':rng.choice(['443','445','53']),'result':'allowed','classification':'benign'})
write('change_records.csv',[
{'id':'CHG-BEN-1','_time':ts(15),'host':'APP-06','change':'CHG-2026-4412','owner':'Endpoint Engineering','scope':'ACMESupportAgent rollout','approved':'yes','classification':'benign'},
{'id':'CHG-GAP-1','_time':ts(25),'host':'ENG-WS-17','change':'NONE','owner':'','scope':'WinSupportSvc','approved':'no','classification':'investigate'},
{'id':'CHG-GAP-2','_time':ts(46),'host':'FIN-WS-09','change':'NONE','owner':'','scope':'OneDriveHealth','approved':'no','classification':'investigate'}],lambda i:{'id':f'CHG-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'change':f'CHG-2026-{rng.randint(1000,9999)}','owner':'IT Operations','scope':'routine maintenance','approved':'yes','classification':'benign'})
write('response_activity.csv',[
{'id':'RESP-1','_time':ts(50),'host':'HR-WS-22','actor':r'ACME\\jsmith','action':'preserve task and script evidence','decision':'preserve before containment','classification':'response'},
{'id':'RESP-2','_time':ts(53),'host':'ENG-WS-17','actor':r'ACME\\jsmith','action':'isolate endpoint','decision':'confirmed second-stage execution','classification':'response'},
{'id':'RESP-3','_time':ts(56),'host':'FIN-WS-09','actor':r'ACME\\jsmith','action':'preserve startup configuration','decision':'local persistence supported','classification':'response'},
{'id':'RESP-4','_time':ts(61),'host':'PATCH-01','actor':r'ACME\\jsmith','action':'leave approved task intact','decision':'provenance verified','classification':'response'},
{'id':'RESP-5','_time':ts(62),'host':'APP-06','actor':r'ACME\\jsmith','action':'leave approved service intact','decision':'change record and trust verified','classification':'response'}],lambda i:{'id':f'RESP-N-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'actor':'SOC','action':'routine triage','decision':'no incident linkage','classification':'response'})
wt(R/'README.md','''# Capstone 012: September 2026 — Persistence, Provenance, and Scope\n\n**Field exercise:** multi-stage investigation with purposeful moderate noise  \n**Expected time:** 90–150 minutes\n\nThe exercise starts with a Microsoft-looking scheduled task on `HR-WS-22`. The chain reaches `ENG-WS-17` through remote service creation and later surfaces as user-context startup persistence on `FIN-WS-09`. Nearby legitimate patch automation, endpoint-management service installation, application startup, and enterprise logon policy are deliberately mixed into the evidence.\n\nThe analyst must build the timeline, prove which mechanisms belong to the incident, preserve benign look-alikes, decide scope and confidence, and make containment choices without treating every administrative mechanism as attacker-controlled.\n\n## Data\nTen platform-portable CSV lookups contain **10,000 records each — 100,000 synthetic records total**. Generation is deterministic with seed `20260921`.''')
wt(R/'prior-three-weeks-coverage.md','''# Prior Three Weeks Coverage\n\n| Hunt | Theme | Capstone use |\n|---|---|---|\n| 009 | Scheduled task vs admin automation | Initial persistence on HR-WS-22; compare against approved patch automation |\n| 010 | Service installation vs endpoint management | Remote service creation on ENG-WS-17; compare against SCCM-managed ACMESupportAgent |\n| 011 | Startup configuration provenance | User-context startup persistence on FIN-WS-09; distinguish from GPO/application startup |''')
wt(R/'attack-narrative.md','''# Attack Narrative\n\nA locally created Microsoft-looking scheduled task on `HR-WS-22` executes an untrusted PowerShell script. The script opens TLS to `203.0.113.77`, then uses `sc.exe` to create `WinSupportSvc` on `ENG-WS-17`. The new service runs as LocalSystem from an untrusted path and contacts the same external destination. Later, `OneDriveHealth` appears in `ACME\\lchen`'s startup configuration on `FIN-WS-09`; its untrusted script executes at logon and contacts the same destination.\n\nLegitimate look-alikes include the approved `\\ACME\\Patch\\TelemetryCheck` task on `PATCH-01`, SCCM deployment of `ACMESupportAgent` on `APP-06`, a signed Teams updater, and centrally managed `mapdrives.cmd`.\n\nThe supplied evidence supports a three-host incident chain and three distinct persistence mechanisms. It does not establish how the attacker initially obtained `ACME\\mgarcia`, what the TLS payload contained, or that central policy/SCCM infrastructure was compromised.''')
wt(R/'analyst-hunt-guide.md','''# Analyst Hunt Guide\n\n1. Start from CAP-001 and build a timestamped timeline.\n2. Prove or reject scheduled-task persistence on HR-WS-22.\n3. Follow cross-host activity to ENG-WS-17 and determine whether WinSupportSvc is legitimate management or attacker-created.\n4. Explain why ACMESupportAgent on APP-06 is not part of the incident.\n5. Investigate OneDriveHealth on FIN-WS-09 and separate it from Teams and MapDrives.\n6. Correlate artifact trust, provenance, change records, process ancestry, and network destinations.\n7. State confirmed scope, confidence, and evidence gaps.\n8. Make containment decisions without destroying legitimate enterprise mechanisms.''')
wt(R/'investigation-worksheet.md','''# Investigation Worksheet\n\n## Timeline\n| Time | Host | Evidence | Interpretation | Confidence |\n|---|---|---|---|---|\n\n## Mechanism decisions\n| Mechanism | Host | Provenance | Incident-linked? | Evidence |\n|---|---|---|---|---|\n\n## Scope\nConfirmed hosts:\n\nSuspected but unconfirmed:\n\nExplicitly excluded:\n\n## Evidence gaps\n## Containment tradeoffs\n## Final confidence statement''')
wt(R/'data-dictionary.md','''# Data Dictionary\n\nTen CSV lookups are provided: `detection_results`, `scheduled_task`, `endpoint_service`, `startup_config`, `endpoint_process`, `endpoint_file`, `software_trust`, `network_activity`, `change_records`, and `response_activity`. Every lookup contains exactly 10,000 records and uses UTC ISO-8601 timestamps.''')
wt(R/'sample-spl.md','''# Sample SPL\n\n```spl\n| inputlookup detection_results.csv\n| search id="CAP-*"\n| sort 0 _time\n```\n\n```spl\n| inputlookup network_activity.csv\n| search dest="203.0.113.77"\n| sort 0 _time\n| table _time src dest user process port classification\n```\n\n```spl\n| inputlookup endpoint_process.csv\n| search host IN ("HR-WS-22","ENG-WS-17","FIN-WS-09")\n| sort 0 _time\n| table _time host user parent process command classification\n```\n\n```spl\n| inputlookup change_records.csv\n| search host IN ("ENG-WS-17","APP-06","FIN-WS-09")\n| table _time host change owner scope approved classification\n```''')
wt(R/'response-plan.md','''# Response Plan\n\nPreserve the scheduled-task definition and script on HR-WS-22, WinSupportSvc configuration/binary on ENG-WS-17, and OneDriveHealth startup configuration/script on FIN-WS-09 before removal. Isolate the three confirmed hosts according to operational impact and credential exposure. Hunt the exact task name/path, service name/path, startup item/path, relevant user accounts, and `203.0.113.77` across the estate.\n\nDo not disable the approved patch task on PATCH-01, ACMESupportAgent on APP-06, Teams startup, or the enterprise MapDrives policy based on this evidence. Validate those mechanisms and leave them intact unless additional evidence changes the scope. Preserve the distinction between confirmed compromise and administrative proximity.''')
wt(R/'answer-key.json',json.dumps({'seed':SEED,'lookups':10,'rows_per_lookup':N,'total_records':100000,'confirmed_hosts':['HR-WS-22','ENG-WS-17','FIN-WS-09'],'incident_mechanisms':['scheduled task TelemetryCheck','WinSupportSvc','OneDriveHealth startup'],'benign_lookalikes':['ACME Patch TelemetryCheck','ACMESupportAgent','Teams startup','MapDrives GPO'],'not_proven':['initial credential access','TLS payload contents','central policy compromise','SCCM compromise']},indent=2))
wt(R/'validation-report.md','''# Validation Report\n\nGenerated deterministically with seed **20260921**. Validator requires ten lookups, exactly **10,000 rows per lookup / 100,000 total records**, all three incident stages, all four benign look-alikes, cross-host service activity, responder actions, and explicit evidence gaps.''')
wt(R/'validate_lab.py','''from pathlib import Path\nimport csv\nR=Path(__file__).resolve().parent\nnames=['detection_results.csv','scheduled_task.csv','endpoint_service.csv','startup_config.csv','endpoint_process.csv','endpoint_file.csv','software_trust.csv','network_activity.csv','change_records.csv','response_activity.csv']\nfor n in names:\n rows=list(csv.DictReader((R/'data'/n).open(encoding='utf-8'))); assert len(rows)==10000,(n,len(rows))\nassert any(r['id']=='TASK-INC-1' for r in csv.DictReader((R/'data'/'scheduled_task.csv').open()))\nassert any(r['id']=='SVC-INC-1' for r in csv.DictReader((R/'data'/'endpoint_service.csv').open()))\nassert any(r['id']=='START-INC-1' for r in csv.DictReader((R/'data'/'startup_config.csv').open()))\nprint('PASS: 10 lookups x 10,000 records = 100,000')''')
wt(A/'default'/'app.conf','''[install]\nis_configured = 0\n[ui]\nis_visible = 1\nlabel = After the Detection - September 2026 Capstone\n[launcher]\nauthor = WiseHawk Technologies\nversion = 1.0.0\ndescription = Persistence, Provenance, and Scope''')
wt(A/'metadata'/'default.meta','''[]\naccess = read : [ * ], write : [ admin ]\nexport = system''')
wt(A/'default'/'data'/'ui'/'nav'/'default.xml','<nav search_view="search"><view name="capstone_012" default="true"/><view name="search"/></nav>')
wt(A/'default'/'data'/'ui'/'views'/'capstone_012.xml','<form version="1.1" theme="dark"><label>September 2026 Capstone</label><row><panel><table><search><query>| inputlookup detection_results.csv | search id="CAP-*" | sort 0 _time</query></search></table></panel></row></form>')
wt(A/'README.md','Copy `after_detection_capstone_012` into `$SPLUNK_HOME/etc/apps/` and restart Splunk. Bundled CSV lookups require no index.')
print('Generated 100,000 records')
