[install]
is_configured = 0
[ui]
is_visible = 1
label = After the Detection - August Capstone
[launcher]
author = WiseHawk Technologies
version = 1.0.0
description = Hunt 008 - August 2026 Monthly Capstone
