from pathlib import Path
from datetime import datetime,timedelta,timezone
import csv,random,hashlib,json
R=Path(__file__).resolve().parent; D=R/'data'; L=R/'splunk'/'after_detection_hunt_009'/'lookups'
SEED=20260831; N=1800; rng=random.Random(SEED); base=datetime(2026,8,31,12,0,tzinfo=timezone.utc); t0=base+timedelta(hours=2,minutes=26)
hosts=['HR-WS-22','MGMT-01','APP-03','FILE-02','JUMP-01','DC-01','PATCH-01']; users=[r'ACME\kpatel',r'ACME\svc_patch',r'ACME\jsmith',r'ACME\admin.ops',r'NT AUTHORITY\SYSTEM']
def ts(d): return d.strftime('%Y-%m-%dT%H:%M:%SZ')
def noise_time(): return ts(base+timedelta(seconds=rng.randint(0,5*86400)))
def out(name,rows):
    D.mkdir(parents=True,exist_ok=True); L.mkdir(parents=True,exist_ok=True); fields=list(rows[0])
    for p in (D/name,L/name):
        with p.open('w',newline='',encoding='utf-8') as f:
            w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(rows)
def pad(rows,maker):
    rows=list(rows)
    while len(rows)<N: rows.append(maker(len(rows)))
    rows.sort(key=lambda x:x.get('_time','')); return rows
def txt(path,s): path.parent.mkdir(parents=True,exist_ok=True); path.write_text(s.strip()+'\n',encoding='utf-8')
# Detections
rows=[
{'detection_id':'ATD-009-001','_time':ts(t0),'severity':'medium','title':'New Scheduled Task Created','host':'HR-WS-22','user':r'ACME\kpatel','classification':'investigate','note':'Microsoft-looking task path'},
{'detection_id':'ATD-009-002','_time':ts(t0+timedelta(seconds=14)),'severity':'high','title':'Scheduled Task Launches PowerShell','host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','classification':'investigate','note':'hidden PowerShell from ProgramData'},
{'detection_id':'ATD-009-003','_time':ts(t0+timedelta(minutes=2)),'severity':'high','title':'Unsigned DLL Written to ProgramData','host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','classification':'investigate','note':'payload follows task execution'},
{'detection_id':'ATD-009-004','_time':ts(t0+timedelta(minutes=8)),'severity':'medium','title':'Similar Task Name on PATCH-01','host':'PATCH-01','user':r'ACME\svc_patch','classification':'benign','note':'approved patch automation'},
{'detection_id':'ATD-009-005','_time':ts(t0+timedelta(minutes=11)),'severity':'medium','title':'Task Disabled by Responder','host':'HR-WS-22','user':r'ACME\jsmith','classification':'response','note':'IR action'},
{'detection_id':'ATD-009-006','_time':ts(t0+timedelta(minutes=15)),'severity':'high','title':'Persistence Scope Review','host':'HR-WS-22','user':r'ACME\kpatel','classification':'decision','note':'persistence confirmed on HR-WS-22; propagation not proven'}]
out('detection_results.csv',pad(rows,lambda i:{'detection_id':f'ATD-009-{i+100:05d}','_time':noise_time(),'severity':rng.choice(['low','medium']),'title':rng.choice(['Scheduled Task Review','PowerShell Review','Administrative Change Review']),'host':rng.choice(hosts),'user':rng.choice(users),'classification':'context','note':'background detection'}))
# Scheduled tasks
rows=[
{'event_id':'TASK-INC-001','_time':ts(t0),'host':'HR-WS-22','user':r'ACME\kpatel','task_name':r'\Microsoft\Windows\Update\TelemetryCheck','action':'created','task_command':r'powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\ProgramData\WinCache\check.ps1','run_as':r'NT AUTHORITY\SYSTEM','classification':'investigate','note':'plausible name; unusual action and path'},
{'event_id':'TASK-INC-002','_time':ts(t0+timedelta(seconds=14)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','task_name':r'\Microsoft\Windows\Update\TelemetryCheck','action':'started','task_command':r'powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\ProgramData\WinCache\check.ps1','run_as':r'NT AUTHORITY\SYSTEM','classification':'investigate','note':'task executes'},
{'event_id':'TASK-BEN-001','_time':ts(t0+timedelta(minutes=8)),'host':'PATCH-01','user':r'ACME\svc_patch','task_name':r'\ACME\Patch\TelemetryCheck','action':'created','task_command':r'powershell.exe -NoProfile -File C:\ACME\Patch\TelemetryCheck.ps1','run_as':r'ACME\svc_patch','classification':'benign','note':'approved patch automation'},
{'event_id':'TASK-BEN-002','_time':ts(t0+timedelta(minutes=8,seconds=10)),'host':'PATCH-01','user':r'ACME\svc_patch','task_name':r'\ACME\Patch\TelemetryCheck','action':'started','task_command':r'powershell.exe -NoProfile -File C:\ACME\Patch\TelemetryCheck.ps1','run_as':r'ACME\svc_patch','classification':'benign','note':'approved patch task starts'},
{'event_id':'TASK-RESP-001','_time':ts(t0+timedelta(minutes=11)),'host':'HR-WS-22','user':r'ACME\jsmith','task_name':r'\Microsoft\Windows\Update\TelemetryCheck','action':'disabled','task_command':r'powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\ProgramData\WinCache\check.ps1','run_as':r'NT AUTHORITY\SYSTEM','classification':'response','note':'responder disables task'},
{'event_id':'TASK-RESP-002','_time':ts(t0+timedelta(minutes=12)),'host':'HR-WS-22','user':r'ACME\jsmith','task_name':r'\Microsoft\Windows\Update\TelemetryCheck','action':'exported','task_command':'schtasks /Query /XML','run_as':r'ACME\jsmith','classification':'response','note':'task XML preserved'},
{'event_id':'TASK-CTX-001','_time':ts(t0-timedelta(minutes=19)),'host':'HR-WS-22','user':r'ACME\admin.ops','task_name':r'\ACME\Inventory\Daily','action':'started','task_command':r'C:\ACME\Inventory\inventory.exe --daily','run_as':r'NT AUTHORITY\SYSTEM','classification':'benign','note':'known inventory task'}]
out('scheduled_task.csv',pad(rows,lambda i:{'event_id':f'TASK-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'task_name':rng.choice([r'\Microsoft\Windows\Update\Maintenance',r'\ACME\Patch\DailyScan',r'\Microsoft\Windows\DiskCleanup']),'action':rng.choice(['created','updated','started','completed']),'task_command':rng.choice(['UsoClient.exe StartScan',r'powershell.exe -File C:\ACME\Patch\scan.ps1','cleanmgr.exe /AUTOCLEAN']),'run_as':rng.choice([r'NT AUTHORITY\SYSTEM',r'ACME\svc_patch']),'classification':'benign','note':'routine scheduled task'}))
# Processes
rows=[
{'event_id':'PROC-INC-001','_time':ts(t0+timedelta(seconds=14)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','parent_process_name':'taskeng.exe','process_name':'powershell.exe','process_id':'7440','command_line':r'powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\ProgramData\WinCache\check.ps1','classification':'investigate','note':'scheduled task action'},
{'event_id':'PROC-INC-002','_time':ts(t0+timedelta(seconds=26)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','parent_process_name':'powershell.exe','process_name':'rundll32.exe','process_id':'7488','command_line':r'rundll32.exe C:\ProgramData\WinCache\telemetry.dll,Start','classification':'investigate','note':'task launches DLL'},
{'event_id':'PROC-INC-003','_time':ts(t0+timedelta(minutes=2,seconds=20)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','parent_process_name':'powershell.exe','process_name':'cmd.exe','process_id':'7516','command_line':r'cmd.exe /c ipconfig /all > C:\ProgramData\WinCache\net.txt','classification':'investigate','note':'system discovery'},
{'event_id':'PROC-BEN-001','_time':ts(t0+timedelta(minutes=8,seconds=10)),'host':'PATCH-01','user':r'ACME\svc_patch','parent_process_name':'taskeng.exe','process_name':'powershell.exe','process_id':'6120','command_line':r'powershell.exe -NoProfile -File C:\ACME\Patch\TelemetryCheck.ps1','classification':'benign','note':'approved patch task'},
{'event_id':'PROC-BEN-002','_time':ts(t0+timedelta(minutes=8,seconds=22)),'host':'PATCH-01','user':r'ACME\svc_patch','parent_process_name':'powershell.exe','process_name':'patch-agent.exe','process_id':'6144','command_line':'patch-agent.exe --inventory --report MGMT-01','classification':'benign','note':'approved patch inventory'},
{'event_id':'PROC-RESP-001','_time':ts(t0+timedelta(minutes=11,seconds=20)),'host':'HR-WS-22','user':r'ACME\jsmith','parent_process_name':'explorer.exe','process_name':'cmd.exe','process_id':'8212','command_line':'schtasks /Query /XML','classification':'response','note':'responder triage'}]
out('endpoint_process.csv',pad(rows,lambda i:{'event_id':f'PROC-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'parent_process_name':rng.choice(['taskeng.exe','svchost.exe','explorer.exe','services.exe']),'process_name':rng.choice(['powershell.exe','cmd.exe','inventory.exe','patch-agent.exe']),'process_id':str(rng.randint(1000,16000)),'command_line':'routine process','classification':'benign','note':'routine process'}))
# Files
rows=[
{'event_id':'FILE-INC-001','_time':ts(t0-timedelta(seconds=8)),'host':'HR-WS-22','user':r'ACME\kpatel','action':'create','file_path':r'C:\ProgramData\WinCache\check.ps1','source_process':'powershell.exe','classification':'investigate','note':'script staged before task creation'},
{'event_id':'FILE-INC-002','_time':ts(t0+timedelta(minutes=2)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','action':'create','file_path':r'C:\ProgramData\WinCache\telemetry.dll','source_process':'powershell.exe','classification':'investigate','note':'unsigned DLL written'},
{'event_id':'FILE-INC-003','_time':ts(t0+timedelta(minutes=2,seconds=21)),'host':'HR-WS-22','user':r'NT AUTHORITY\SYSTEM','action':'create','file_path':r'C:\ProgramData\WinCache\net.txt','source_process':'cmd.exe','classification':'investigate','note':'discovery output'},
{'event_id':'FILE-BEN-001','_time':ts(t0+timedelta(minutes=8)),'host':'PATCH-01','user':r'ACME\svc_patch','action':'read','file_path':r'C:\ACME\Patch\TelemetryCheck.ps1','source_process':'powershell.exe','classification':'benign','note':'approved patch script'},
{'event_id':'FILE-RESP-001','_time':ts(t0+timedelta(minutes=12,seconds=25)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'read','file_path':r'C:\ProgramData\WinCache\telemetry.dll','source_process':'powershell.exe','classification':'response','note':'responder hashes artifact'}]
out('endpoint_file.csv',pad(rows,lambda i:{'event_id':f'FILE-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':rng.choice(users),'action':rng.choice(['read','create','modify']),'file_path':rng.choice([r'C:\Windows\Temp\app.log',r'C:\ACME\Patch\state.json',r'C:\ProgramData\inventory.db']),'source_process':rng.choice(['powershell.exe','patch-agent.exe','inventory.exe']),'classification':'benign','note':'routine file activity'}))
# Network
rows=[
{'event_id':'NET-INC-001','_time':ts(t0+timedelta(seconds=35)),'src_host':'HR-WS-22','dest_host':'203.0.113.55','user':r'NT AUTHORITY\SYSTEM','process_name':'powershell.exe','dest_port':'443','action':'allowed','bytes_out':'4120','classification':'investigate','note':'task payload contacts external host'},
{'event_id':'NET-INC-002','_time':ts(t0+timedelta(minutes=4)),'src_host':'HR-WS-22','dest_host':'203.0.113.55','user':r'NT AUTHORITY\SYSTEM','process_name':'rundll32.exe','dest_port':'443','action':'allowed','bytes_out':'22140','classification':'investigate','note':'follow-on TLS; content unknown'},
{'event_id':'NET-BEN-001','_time':ts(t0+timedelta(minutes=8,seconds=25)),'src_host':'PATCH-01','dest_host':'MGMT-01','user':r'ACME\svc_patch','process_name':'patch-agent.exe','dest_port':'443','action':'allowed','bytes_out':'18320','classification':'benign','note':'approved patch reporting'},
{'event_id':'NET-RESP-001','_time':ts(t0+timedelta(minutes=11,seconds=30)),'src_host':'JUMP-01','dest_host':'HR-WS-22','user':r'ACME\jsmith','process_name':'mstsc.exe','dest_port':'3389','action':'allowed','bytes_out':'18000','classification':'response','note':'authorized responder'}]
out('network_activity.csv',pad(rows,lambda i:{'event_id':f'NET-{i:05d}','_time':noise_time(),'src_host':rng.choice(hosts),'dest_host':rng.choice(hosts+['203.0.113.55']),'user':rng.choice(users),'process_name':rng.choice(['powershell.exe','patch-agent.exe','inventory.exe','System']),'dest_port':rng.choice(['443','445','5985','53']),'action':'allowed','bytes_out':str(rng.randint(100,80000)),'classification':'benign','note':'routine network'}))
# Trust
rows=[
{'event_id':'TRUST-INC-001','_time':ts(t0+timedelta(minutes=2,seconds=5)),'host':'HR-WS-22','file_path':r'C:\ProgramData\WinCache\telemetry.dll','sha256':'a4d9f1b7c99b09d081716e20f221eb517bd3c13b689f8eb1d25a5e74c491dd8f','signature_status':'unsigned','publisher':'','classification':'investigate','note':'unknown unsigned payload'},
{'event_id':'TRUST-INC-002','_time':ts(t0+timedelta(seconds=5)),'host':'HR-WS-22','file_path':r'C:\ProgramData\WinCache\check.ps1','sha256':'7d4815dfb5d29b15cbbd9af8a135f856e932e48b1e7a22b9382a2847b34ed268','signature_status':'unsigned','publisher':'','classification':'investigate','note':'not approved automation'},
{'event_id':'TRUST-BEN-001','_time':ts(t0+timedelta(minutes=8,seconds=2)),'host':'PATCH-01','file_path':r'C:\ACME\Patch\TelemetryCheck.ps1','sha256':'1b985d01369907d8f61b4d6116a5cb0eb5a31822b82a29eb28d3d376c80c1e6a','signature_status':'trusted_internal','publisher':'ACME IT Automation','classification':'benign','note':'approved patch script'}]
out('software_trust.csv',pad(rows,lambda i:{'event_id':f'TRUST-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'file_path':rng.choice([r'C:\Windows\System32\cleanmgr.exe',r'C:\ACME\Patch\TelemetryCheck.ps1',r'C:\ACME\Inventory\inventory.exe']),'sha256':hashlib.sha256(f'benign-{i}'.encode()).hexdigest(),'signature_status':rng.choice(['signed','trusted_internal']),'publisher':rng.choice(['Microsoft Windows','ACME IT Automation']),'classification':'benign','note':'routine trust context'}))
# Assets
rows=[{'asset_id':f'AST-{i+1:05d}','host':(hosts[i%len(hosts)] if i<120 else f'LAB-ASSET-{i:04d}'),'role':rng.choice(['workstation','management server','application server']),'owner':rng.choice(['HR','Infrastructure','IT Operations']),'criticality':rng.choice(['medium','high']),'approved_task_roots':r'\ACME\Patch;\ACME\Inventory;\Microsoft\Windows\Defrag','note':'synthetic asset context'} for i in range(N)]
out('asset_inventory.csv',rows)
# Change records
rows=[
{'change_id':'CHG-BEN-001','_time':ts(t0+timedelta(minutes=7)),'host':'PATCH-01','owner':'Endpoint Team','change_type':'patch_cycle','approved':'yes','related_task':r'\ACME\Patch\TelemetryCheck','classification':'benign','note':'documents approved patch task'},
{'change_id':'CHG-CTX-001','_time':ts(t0-timedelta(hours=2)),'host':'HR-WS-22','owner':'IT Operations','change_type':'inventory_update','approved':'yes','related_task':r'\ACME\Inventory\Daily','classification':'benign','note':'documents known inventory task'},
{'change_id':'CHG-GAP-001','_time':ts(t0),'host':'HR-WS-22','owner':'','change_type':'none_found','approved':'no','related_task':r'\Microsoft\Windows\Update\TelemetryCheck','classification':'investigate','note':'no approved change matches suspicious task'}]
out('change_records.csv',pad(rows,lambda i:{'change_id':f'CHG-{i+1000:05d}','_time':noise_time(),'host':rng.choice(hosts),'owner':rng.choice(['IT Operations','Endpoint Team','Infrastructure']),'change_type':rng.choice(['patch_cycle','inventory_update','maintenance']),'approved':'yes','related_task':rng.choice([r'\ACME\Patch\DailyScan',r'\ACME\Inventory\Daily']),'classification':'benign','note':'routine change record'}))
# Response
rows=[
{'event_id':'RESP-INC-001','_time':ts(t0+timedelta(minutes=9)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'scope_scheduled_task','classification':'response','note':'review task definition creator action run-as'},
{'event_id':'RESP-INC-002','_time':ts(t0+timedelta(minutes=11)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'disable_task','classification':'response','note':'stop persistence from re-running'},
{'event_id':'RESP-INC-003','_time':ts(t0+timedelta(minutes=12)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'preserve_task_xml_and_payload','classification':'response','note':'preserve task definition and WinCache artifacts'},
{'event_id':'RESP-INC-004','_time':ts(t0+timedelta(minutes=14)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'isolate_host','classification':'response','note':'contain confirmed persistence'},
{'event_id':'RESP-INC-005','_time':ts(t0+timedelta(minutes=16)),'host':'HR-WS-22','user':r'ACME\jsmith','action':'hunt_same_task_and_hashes','classification':'response','note':'estate-wide scope'}]
out('response_activity.csv',pad(rows,lambda i:{'event_id':f'RESP-{i:05d}','_time':noise_time(),'host':rng.choice(hosts),'user':'SOC-AUTOMATION','action':rng.choice(['review_alert','collect_logs','query_task']),'classification':'response','note':'routine response'}))
# Documentation and app
README=r'''# Hunt 009: Scheduled Task or Admin Automation?\n\n**Difficulty:** Guided, moderate noise  \n**Expected time:** 35–50 minutes  \n**Starting point:** A new scheduled task appears on `HR-WS-22` under a Microsoft-looking path.\n\nThe task name is plausible: `\\Microsoft\\Windows\\Update\\TelemetryCheck`. That is not enough to call it malicious.\n\nThe analyst must compare task metadata, creator, run-as account, command path, process ancestry, file trust, network behavior, and approved change records.\n\n## Quick start\n1. Start with `detection_results.csv`.\n2. Inspect `scheduled_task.csv`.\n3. Follow execution into process and file data.\n4. Compare the approved `PATCH-01` look-alike.\n5. Check trust and change records.\n6. Decide what proves persistence on `HR-WS-22` and what does not prove propagation.\n\n## Data\nNine platform-portable CSV lookups contain 1,800 records each, for **16,200 total synthetic records**.'''
txt(R/'README.md',README)
txt(R/'attack-narrative.md',r'''# Attack Narrative\n\n`ACME\\kpatel` stages `C:\\ProgramData\\WinCache\\check.ps1` and creates `\\Microsoft\\Windows\\Update\\TelemetryCheck` to run hidden PowerShell as `SYSTEM`. The task launches `telemetry.dll` through `rundll32.exe`, performs discovery, and opens TLS to `203.0.113.55`.\n\n`PATCH-01` creates a similarly named approved task using `ACME\\svc_patch` and a trusted internal script. `HR-WS-22` also has a known ACME inventory task.\n\nThe evidence supports malicious scheduled-task persistence on `HR-WS-22`; it does not prove propagation or the semantic content of the TLS sessions.''')
txt(R/'analyst-hunt-guide.md','''# Analyst Hunt Guide\n\n1. Read the task metadata, not just the name.\n2. Follow task start into process ancestry.\n3. Check payload trust.\n4. Compare the approved PATCH-01 look-alike.\n5. Check change records and known task roots.\n6. State the persistence decision and confidence.\n7. Hunt estate-wide without assuming propagation.''')
txt(R/'investigation-worksheet.md','''# Investigation Worksheet\n\n| Entity / Task | Creator | Run-as | Command / Payload | Change record | Trust context | Decision | Confidence |\n|---|---|---|---|---|---|---|---|\n| HR-WS-22 / TelemetryCheck | | | | | | | |\n| PATCH-01 / TelemetryCheck | | | | | | | |\n| HR-WS-22 / ACME Inventory | | | | | | | |\n\n## Process ancestry\n## File and trust pivots\n## Network context\n## Persistence decision\n## Estate-wide scope query\n## Evidence gaps''')
txt(R/'data-dictionary.md','''# Data Dictionary\n\nNine lookups, 1,800 records each: asset inventory, change records, detections, endpoint file, endpoint process, network activity, response activity, scheduled tasks, and software trust. All timestamps are UTC ISO 8601.''')
txt(R/'sample-spl.md',r'''# Sample SPL\n\n```spl\n| inputlookup detection_results.csv | search detection_id="ATD-009-*" | sort 0 _time\n```\n\n```spl\n| inputlookup scheduled_task.csv | search task_name="*TelemetryCheck*" | sort 0 _time | table _time host user task_name action task_command run_as note\n```\n\n```spl\n| inputlookup endpoint_process.csv | search host="HR-WS-22" | sort 0 _time | table _time user parent_process_name process_name command_line note\n```\n\n```spl\n| inputlookup software_trust.csv | search file_path="*TelemetryCheck*" OR file_path="*WinCache*" | table _time host file_path signature_status publisher sha256 note\n```''')
txt(R/'response-plan.md',r'''# Response Plan / Expected Decision\n\n`HR-WS-22` has high-confidence malicious scheduled-task persistence. Preserve the task XML, script, DLL, hashes, and process/network evidence; disable the task; isolate the host; then hunt the exact task path, hashes, WinCache path, and external destination across the estate.\n\nDo not claim persistence on another host until matching evidence is found. The approved `PATCH-01` task is a comparison point, not proof of propagation.''')
txt(R/'answer-key.json',json.dumps({'seed':SEED,'lookup_count':9,'rows_per_lookup':N,'total_records':9*N,'primary_host':'HR-WS-22','suspicious_task':r'\Microsoft\Windows\Update\TelemetryCheck','expected_decision':'High-confidence malicious scheduled-task persistence on HR-WS-22.','not_proven':['same persistence on another host','content of TLS sessions','data theft or command-and-control semantics']},indent=2))
validator='''from pathlib import Path\nimport csv\nR=Path(__file__).resolve().parent\nnames=["asset_inventory.csv","change_records.csv","detection_results.csv","endpoint_file.csv","endpoint_process.csv","network_activity.csv","response_activity.csv","scheduled_task.csv","software_trust.csv"]\nfor n in names: assert len(list(csv.DictReader((R/"data"/n).open(encoding="utf-8"))))==1800,(n)\nt=list(csv.DictReader((R/"data"/"scheduled_task.csv").open(encoding="utf-8")))\nassert any(x["event_id"]=="TASK-INC-001" and x["host"]=="HR-WS-22" for x in t)\nassert any(x["event_id"]=="TASK-BEN-001" and x["host"]=="PATCH-01" for x in t)\np=list(csv.DictReader((R/"data"/"endpoint_process.csv").open(encoding="utf-8")))\nassert any(x["event_id"]=="PROC-INC-002" and x["process_name"]=="rundll32.exe" for x in p)\nprint("PASS: 9 lookups x 1,800 = 16,200 records; required Hunt 009 evidence present")'''
txt(R/'validate_lab.py',validator)
txt(R/'validation-report.md','''# Validation Report\n\n- Seed: **20260831**\n- Lookups: **9**\n- Rows per lookup: **1,800**\n- Total records: **16,200**\n- Suspicious scheduled-task persistence: **present**\n- Approved patch look-alike: **present**\n- Known inventory look-alike: **present**\n- Responder activity: **present**\n- Explicit evidence gaps: **present**''')
A=R/'splunk'/'after_detection_hunt_009'; txt(A/'default'/'app.conf','''[install]\nis_configured = 0\n\n[ui]\nis_visible = 1\nlabel = After the Detection - Hunt 009\n\n[launcher]\nauthor = WiseHawk Technologies\nversion = 1.0.0\ndescription = Hunt 009 - Scheduled Task or Admin Automation?'''); txt(A/'metadata'/'default.meta','''[]\naccess = read : [ * ], write : [ admin ]\nexport = system'''); txt(A/'default'/'data'/'ui'/'nav'/'default.xml','<nav search_view="search"><view name="hunt_009_overview" default="true"/><view name="search"/></nav>'); txt(A/'default'/'data'/'ui'/'views'/'hunt_009_overview.xml','''<form version="1.1" theme="dark"><label>Hunt 009 — Scheduled Task or Admin Automation?</label><row><panel><table><search><query>| inputlookup detection_results.csv | search detection_id="ATD-009-*"</query></search></table></panel></row></form>'''); txt(A/'README.md','''# Splunk Lab App\n\nCopy `after_detection_hunt_009` into `$SPLUNK_HOME/etc/apps/` and restart Splunk. Bundled CSV lookups require no index or add-on.''')
print(f'Generated 9 lookups x {N} = {9*N} records with seed {SEED}')