from pathlib import Path
import csv,random,json,hashlib
from datetime import datetime,timedelta,timezone
R=Path(__file__).resolve().parent; D=R/'data'; D.mkdir(parents=True,exist_ok=True)
SEED=20260817; N=1800; rng=random.Random(SEED); base=datetime(2026,8,18,12,tzinfo=timezone.utc); t0=base+timedelta(hours=2,minutes=41)
hosts=['FIN-WS-14','FILE-02','JUMP-01','APP-API-02','DC-01','BACKUP-01','PRINT-01']; users=['ACME\\mrivera','ACME\\svc_backup','ACME\\jsmith','ACME\\svc_print','NT AUTHORITY\\SYSTEM']
def iso(d): return d.strftime('%Y-%m-%dT%H:%M:%SZ')
def w(name,rows):
 p=D/name
 with p.open('w',newline='',encoding='utf-8') as f:
  x=csv.DictWriter(f,fieldnames=list(rows[0]));x.writeheader();x.writerows(rows)
def dt(): return iso(base+timedelta(seconds=rng.randint(0,432000)))
a=[{'event_id':f'AUTH-{i:05d}','_time':dt(),'src_host':rng.choice(hosts),'dest_host':rng.choice(['DC-01','FILE-02','APP-API-02']),'user':rng.choice(users),'protocol':rng.choice(['Kerberos','NTLM','SMB','RDP']),'result':rng.choice(['success','success','success','failure']),'classification':'benign','note':'routine authentication'} for i in range(N-5)]
a += [
{'event_id':'AUTH-INC-001','_time':iso(t0),'src_host':'FIN-WS-14','dest_host':'DC-01','user':'ACME\\mrivera','protocol':'Kerberos','result':'failure','classification':'contained','note':'credential use after password reset from isolated host'},
{'event_id':'AUTH-INC-002','_time':iso(t0+timedelta(minutes=3)),'src_host':'FILE-02','dest_host':'DC-01','user':'ACME\\mrivera','protocol':'Kerberos','result':'success','classification':'investigate','note':'same user succeeds from different host after reset'},
{'event_id':'AUTH-INC-003','_time':iso(t0+timedelta(minutes=3,seconds=4)),'src_host':'FILE-02','dest_host':'FILE-02','user':'ACME\\mrivera','protocol':'SMB','result':'success','classification':'investigate','note':'finance share session'},
{'event_id':'AUTH-BEN-001','_time':iso(t0+timedelta(minutes=4)),'src_host':'BACKUP-01','dest_host':'FILE-02','user':'ACME\\svc_backup','protocol':'SMB','result':'success','classification':'benign','note':'scheduled backup'},
{'event_id':'AUTH-RESP-001','_time':iso(t0+timedelta(minutes=11)),'src_host':'JUMP-01','dest_host':'FILE-02','user':'ACME\\jsmith','protocol':'RDP','result':'success','classification':'response','note':'authorized responder'}]; w('identity_auth.csv',sorted(a,key=lambda x:x['_time']))
p=[{'event_id':f'PROC-{i:05d}','_time':dt(),'host':rng.choice(hosts),'user':rng.choice(users),'parent_process_name':rng.choice(['services.exe','explorer.exe','taskeng.exe']),'process_name':rng.choice(['robocopy.exe','powershell.exe','backup-agent.exe','cmd.exe']),'command_line':'routine process','classification':'benign','note':'routine process'} for i in range(N-5)]
p += [
{'event_id':'PROC-INC-001','_time':iso(t0+timedelta(minutes=3,seconds=9)),'host':'FILE-02','user':'ACME\\mrivera','parent_process_name':'explorer.exe','process_name':'cmd.exe','command_line':'cmd.exe /c dir \\\\FILE-02\\Finance$ && copy \\\\FILE-02\\Finance$\\Q3.xlsx C:\\Users\\Public\\Q3.xlsx','classification':'investigate','note':'interactive finance file access'},
{'event_id':'PROC-INC-002','_time':iso(t0+timedelta(minutes=3,seconds=31)),'host':'FILE-02','user':'ACME\\mrivera','parent_process_name':'cmd.exe','process_name':'powershell.exe','command_line':'powershell.exe -NoProfile -Command Get-ChildItem C:\\Users\\Public\\Q3.xlsx','classification':'investigate','note':'follow-on command'},
{'event_id':'PROC-BEN-001','_time':iso(t0+timedelta(minutes=4,seconds=12)),'host':'FILE-02','user':'ACME\\svc_backup','parent_process_name':'services.exe','process_name':'backup-agent.exe','command_line':'backup-agent.exe --job nightly-finance','classification':'benign','note':'scheduled backup'},
{'event_id':'PROC-RESP-001','_time':iso(t0+timedelta(minutes=11,seconds=20)),'host':'FILE-02','user':'ACME\\jsmith','parent_process_name':'explorer.exe','process_name':'cmd.exe','command_line':'cmd.exe /c whoami && quser && netstat -ano','classification':'response','note':'responder triage'},
{'event_id':'PROC-CTX-001','_time':iso(t0-timedelta(minutes=8)),'host':'FIN-WS-14','user':'ACME\\mrivera','parent_process_name':'powershell.exe','process_name':'rundll32.exe','command_line':'rundll32.exe C:\\ProgramData\\Cache\\stage.dll,Start','classification':'malicious','note':'known prior compromise'}]; w('endpoint_process.csv',sorted(p,key=lambda x:x['_time']))
f=[{'event_id':f'FILE-{i:05d}','_time':dt(),'host':rng.choice(hosts),'user':rng.choice(users),'action':rng.choice(['read','create','modify']),'file_path':rng.choice(['C:\\Backup\\state.db','C:\\Windows\\Temp\\app.log','D:\\Shares\\Finance\\budget.xlsx']),'source_process':rng.choice(['backup-agent.exe','explorer.exe','robocopy.exe']),'classification':'benign','note':'routine file activity'} for i in range(N-4)]
f += [
{'event_id':'FILE-INC-001','_time':iso(t0+timedelta(minutes=3,seconds=12)),'host':'FILE-02','user':'ACME\\mrivera','action':'read','file_path':'D:\\Shares\\Finance\\Q3.xlsx','source_process':'cmd.exe','classification':'investigate','note':'finance share accessed'},
{'event_id':'FILE-INC-002','_time':iso(t0+timedelta(minutes=3,seconds=18)),'host':'FILE-02','user':'ACME\\mrivera','action':'create','file_path':'C:\\Users\\Public\\Q3.xlsx','source_process':'cmd.exe','classification':'investigate','note':'local copy created'},
{'event_id':'FILE-BEN-001','_time':iso(t0+timedelta(minutes=4,seconds=14)),'host':'FILE-02','user':'ACME\\svc_backup','action':'read','file_path':'D:\\Shares\\Finance\\Q3.xlsx','source_process':'backup-agent.exe','classification':'benign','note':'scheduled backup read'},
{'event_id':'FILE-RESP-001','_time':iso(t0+timedelta(minutes=12)),'host':'FILE-02','user':'ACME\\jsmith','action':'create','file_path':'C:\\IR\\file02_triage.txt','source_process':'cmd.exe','classification':'response','note':'responder collection'}]; w('endpoint_file.csv',sorted(f,key=lambda x:x['_time']))
for name,kind in [('network_activity.csv','network'),('asset_inventory.csv','asset'),('response_activity.csv','response'),('investigation_findings.csv','finding')]:
 rows=[]
 for i in range(N): rows.append({'event_id':f'{kind.upper()}-{i:05d}','_time':dt(),'host':rng.choice(hosts),'user':rng.choice(users),'detail':'purposeful background context','classification':'benign','note':'synthetic noise'})
 w(name,rows)
ia=[{'event_id':f'ACT-{i:05d}','_time':dt(),'actor':'ACME\\helpdesk1','target_user':rng.choice(users),'action':'ticket_review','result':'success','classification':'benign','note':'routine identity administration'} for i in range(N-4)]
ia += [
{'event_id':'ACT-INC-001','_time':iso(t0-timedelta(minutes=6)),'actor':'ACME\\helpdesk1','target_user':'ACME\\mrivera','action':'password_reset','result':'success','classification':'response','note':'reset after confirmed compromise'},
{'event_id':'ACT-INC-002','_time':iso(t0-timedelta(minutes=5)),'actor':'SOC-AUTOMATION','target_user':'ACME\\mrivera','action':'revoke_interactive_sessions','result':'partial','classification':'response','note':'endpoint sessions targeted'},
{'event_id':'ACT-INC-003','_time':iso(t0+timedelta(minutes=8)),'actor':'ACME\\jsmith','target_user':'ACME\\mrivera','action':'disable_account','result':'success','classification':'response','note':'disabled after post-reset use'},
{'event_id':'ACT-INC-004','_time':iso(t0+timedelta(minutes=9)),'actor':'ACME\\jsmith','target_user':'ACME\\mrivera','action':'revoke_all_sessions','result':'success','classification':'response','note':'full revocation'}]; w('identity_admin.csv',sorted(ia,key=lambda x:x['_time']))
d=[{'detection_id':f'ATD-007-{i+10:05d}','_time':dt(),'severity':'low','title':'Background Review','host':rng.choice(hosts),'user':rng.choice(users),'expected_decision':'context','note':'background detection'} for i in range(N-5)]
d += [
{'detection_id':'ATD-007-001','_time':iso(t0-timedelta(minutes=8)),'severity':'critical','title':'Known Compromise on FIN-WS-14','host':'FIN-WS-14','user':'ACME\\mrivera','expected_decision':'confirmed','note':'prior confirmed compromise'},
{'detection_id':'ATD-007-002','_time':iso(t0),'severity':'medium','title':'Credential Use After Reset','host':'FIN-WS-14','user':'ACME\\mrivera','expected_decision':'contained','note':'failed from isolated source'},
{'detection_id':'ATD-007-003','_time':iso(t0+timedelta(minutes=3)),'severity':'high','title':'Successful Authentication After Reset','host':'FILE-02','user':'ACME\\mrivera','expected_decision':'investigate','note':'success from new host'},
{'detection_id':'ATD-007-004','_time':iso(t0+timedelta(minutes=3,seconds=12)),'severity':'high','title':'Finance Share Access by Reset User','host':'FILE-02','user':'ACME\\mrivera','expected_decision':'escalate','note':'auth followed by file access'},
{'detection_id':'ATD-007-005','_time':iso(t0+timedelta(minutes=11)),'severity':'medium','title':'Admin Access to Scoped Host','host':'FILE-02','user':'ACME\\jsmith','expected_decision':'response','note':'authorized responder'}]; w('detection_results.csv',sorted(d,key=lambda x:x['_time']))
(R/'README.md').write_text('''# Hunt 007: Account Use After Containment\n\n**Difficulty:** Guided, moderate noise  \n**Expected time:** 30–45 minutes  \n\n`FIN-WS-14` is confirmed compromised, isolated, and `ACME\\mrivera` has a password reset. Three minutes later, the same user successfully authenticates from `FILE-02`, followed by command execution and finance-share access.\n\nThe hunt is about what containment changes: a username alone is not enough. Compare source host, result, timing, process execution, file access, scheduled backup activity, and responder activity before deciding whether `FILE-02` belongs in incident scope.\n\n## Quick start\n1. Start with `detection_results.csv`.\n2. Build the containment timeline from `identity_admin.csv`.\n3. Compare post-reset authentication in `identity_auth.csv`.\n4. Pivot to process and file activity on `FILE-02`.\n5. Separate backup and responder activity.\n6. Make a scope and containment decision.\n\n## Data\nNine portable CSV lookups contain 1,800 records each: **16,200 synthetic records**.\n''',encoding='utf-8')
(R/'analyst-hunt-guide.md').write_text('# Analyst Hunt Guide\n\nBuild the containment timeline, compare post-reset authentication by source and result, pivot to FILE-02 process/file activity, remove backup and responder look-alikes, then state scope, confidence, and response tradeoff.\n',encoding='utf-8')
(R/'investigation-worksheet.md').write_text('# Investigation Worksheet\n\n| Entity | Evidence | Benign/response explanation | Scope decision | Confidence | Missing evidence |\n|---|---|---|---|---|---|\n| FIN-WS-14 | | | | | |\n| ACME\\mrivera | | | | | |\n| FILE-02 | | | | | |\n',encoding='utf-8')
(R/'data-dictionary.md').write_text('# Data Dictionary\n\nNine platform-portable CSV lookups; all timestamps are UTC ISO 8601 and each lookup contains 1,800 records.\n',encoding='utf-8')
(R/'sample-spl.md').write_text('''# Sample SPL\n\n```spl\n| inputlookup identity_auth.csv\n| eval _time=strptime(_time,"%Y-%m-%dT%H:%M:%SZ")\n| search user="ACME\\\\mrivera"\n| sort 0 _time\n| table _time src_host dest_host user protocol result classification note\n```\n\n```spl\n| inputlookup endpoint_process.csv\n| eval _time=strptime(_time,"%Y-%m-%dT%H:%M:%SZ")\n| search host="FILE-02"\n| sort 0 _time\n| table _time host user parent_process_name process_name command_line classification note\n```\n''',encoding='utf-8')
(R/'response-plan.md').write_text('# Response Plan\n\nAdd `FILE-02` to incident scope with high confidence. Preserve volatile evidence if operationally feasible, then restrict network access. The evidence does not prove initial access to FILE-02, persistence, or exfiltration of Q3.xlsx.\n',encoding='utf-8')
(R/'attack-narrative.md').write_text('# Attack Narrative\n\nAfter isolation and password reset, `ACME\\mrivera` succeeds from `FILE-02`, runs `cmd.exe` and PowerShell, reads `D:\\Shares\\Finance\\Q3.xlsx`, and copies it to `C:\\Users\\Public\\Q3.xlsx`. Backup and responder activity occur nearby as look-alikes.\n',encoding='utf-8')
(R/'answer-key.json').write_text(json.dumps({'seed':SEED,'lookups':9,'rows_per_lookup':N,'total_records':9*N,'new_scope_host':'FILE-02','decision':'add FILE-02 to incident scope with high confidence','not_proven':['initial access','persistence','exfiltration']},indent=2)+'\n')
(R/'validate_lab.py').write_text('''from pathlib import Path\nimport csv\nR=Path(__file__).resolve().parent\nnames=['asset_inventory.csv','identity_admin.csv','identity_auth.csv','network_activity.csv','endpoint_process.csv','endpoint_file.csv','detection_results.csv','investigation_findings.csv','response_activity.csv']\nfor n in names: assert len(list(csv.DictReader((R/'data'/n).open(encoding='utf-8'))))==1800,n\na=list(csv.DictReader((R/'data'/'identity_auth.csv').open(encoding='utf-8'))); assert any(x['event_id']=='AUTH-INC-002' and x['result']=='success' for x in a)\np=list(csv.DictReader((R/'data'/'endpoint_process.csv').open(encoding='utf-8'))); assert any(x['event_id']=='PROC-INC-001' and x['host']=='FILE-02' for x in p)\nprint('PASS: Hunt 007 - 9 lookups, 1,800 rows each, 16,200 records')\n''',encoding='utf-8')
(R/'validation-report.md').write_text('# Validation Report\n\n- Seed: **20260817**\n- Lookups: **9**\n- Rows per lookup: **1,800**\n- Total records: **16,200**\n- Post-reset FILE-02 authentication: **present**\n- Follow-on process/file evidence: **present**\n- Backup and responder look-alikes: **present**\n',encoding='utf-8')
app=R/'splunk'/'after_detection_hunt_007'; (app/'default'/'data'/'ui'/'views').mkdir(parents=True,exist_ok=True); (app/'default'/'data'/'ui'/'nav').mkdir(parents=True,exist_ok=True); (app/'lookups').mkdir(parents=True,exist_ok=True)
(app/'default'/'app.conf').write_text('[install]\nis_configured = 0\n[ui]\nis_visible = 1\nlabel = After the Detection - Hunt 007\n[launcher]\nversion = 1.0.0\ndescription = Hunt 007 - Account Use After Containment\n')
(app/'default'/'data'/'ui'/'nav'/'default.xml').write_text('<nav search_view="search"><view name="hunt_007_overview" default="true"/><view name="search"/></nav>')
(app/'default'/'data'/'ui'/'views'/'hunt_007_overview.xml').write_text('<form version="1.1" theme="dark"><label>Hunt 007 — Account Use After Containment</label><row><panel><table><search><query>| inputlookup detection_results.csv | search detection_id="ATD-007-*" | table _time severity title host user expected_decision note</query></search></table></panel></row></form>')
for p in D.glob('*.csv'): (app/'lookups'/p.name).write_bytes(p.read_bytes())
manifest=[]
for p in sorted(R.rglob('*')):
 if p.is_file() and p.name!='manifest.json': manifest.append({'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
(R/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
